ALTER TABLE users ALTER COLUMN wallet_address TYPE VARCHAR(70);
ALTER TABLE stories ALTER COLUMN user_wallet TYPE VARCHAR(70);
ALTER TABLE likes ALTER COLUMN user_wallet TYPE VARCHAR(70);
ALTER TABLE comments ALTER COLUMN user_wallet TYPE VARCHAR(70);
ALTER TABLE views ALTER COLUMN user_wallet TYPE VARCHAR(70);
ALTER TABLE chat_messages ALTER COLUMN user_wallet TYPE VARCHAR(70);
